name: Run tests on CI env

on:
  push: ~
  pull_request:
    branches: [master, production]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: "lets perfom some actions"
        run: "echo 'hello world from GA'"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B test
